-- ic_trans_to_sale_mv
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_to_sale_mv TO datachangsiam.saleinvoice_transaction
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `creator_code` String,
    `creator_name` String,
    `status_cancel` String,
    `pos_id` String,
    `customer_code` String,
    `customer_name` String,
    `sale_code` String,
    `sale_name` String,
    `doc_type` String,
    `due_date` DateTime,
    `sum_point` Float64,
    `total_value` Float64,
    `total_discount` Float64,
    `total_before_vat` Float64,
    `total_vat_value` Float64,
    `total_after_vat` Float64,
    `total_except_vat` Float64,
    `total_amount` Float64,
    `remark` String,
    `branch_code` String,
    `branch_name` String,
    `department_code` String,
    `department_name` String,
    `side_code` String,
    `side_name` String,
    `project_code` String,
    `project_name` String,
    `job_code` String,
    `job_name` String,
    `allocate_code` String,
    `allocate_name` String,
    `billing_no_array` String,
    `sum_pay_money` Float64,
    `status_payment` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(raw_data, 'payload', 'after', 'creator_code') AS creator_code,
    '' AS creator_name,
    if((JSONExtractString(raw_data, 'payload', 'after', 'is_cancel') IN ('true', '1')), 'Cancel', '') AS status_cancel,
    JSONExtractString(raw_data, 'payload', 'after', 'pos_id') AS pos_id,
    JSONExtractString(raw_data, 'payload', 'after', 'cust_code') AS customer_code,
    '' AS customer_name,
    JSONExtractString(raw_data, 'payload', 'after', 'sale_code') AS sale_code,
    '' AS sale_name,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_type') AS doc_type,
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'due_date'))) AS due_date,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_point') AS sum_point,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_value') AS total_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_discount') AS total_discount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_before_vat') AS total_before_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_vat_value') AS total_vat_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_after_vat') AS total_after_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_except_vat') AS total_except_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_amount') AS total_amount,
    JSONExtractString(raw_data, 'payload', 'after', 'remark') AS remark,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'department_code') AS department_code,
    '' AS department_name,
    JSONExtractString(raw_data, 'payload', 'after', 'side_code') AS side_code,
    '' AS side_name,
    JSONExtractString(raw_data, 'payload', 'after', 'project_code') AS project_code,
    '' AS project_name,
    JSONExtractString(raw_data, 'payload', 'after', 'job_code') AS job_code,
    '' AS job_name,
    JSONExtractString(raw_data, 'payload', 'after', 'allocate_code') AS allocate_code,
    '' AS allocate_name,
    '' AS billing_no_array,
    JSONExtractFloat(raw_data, 'payload', 'after', 'pay_amount') AS sum_pay_money,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 0, 'Outstanding', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 1, 'Partially Paid', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 2, 'Fully Paid', '') AS status_payment,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 2) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'));

-- ic_trans_detail_to_sale_detail_mv
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_detail_to_sale_detail_mv TO datachangsiam.saleinvoice_transaction_detail
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `branch_code` String,
    `branch_name` String,
    `item_code` String,
    `barcode` String,
    `item_name` String,
    `unit_code` String,
    `unit_name` String,
    `wh_code` String,
    `wh_name` String,
    `shelf_code` String,
    `shelf_name` String,
    `qty` Float64,
    `price` Float64,
    `discount_amount` Float64,
    `sum_amount` Float64,
    `sum_of_cost` Float64,
    `average_cost` Float64,
    `stand_value` Float64,
    `divide_value` Float64,
    `tax_type` String,
    `item_brand_code` String,
    `item_brand_name` String,
    `item_pattern_code` String,
    `item_pattern_name` String,
    `item_design_code` String,
    `item_design_name` String,
    `item_grade_code` String,
    `item_grade_name` String,
    `item_model_code` String,
    `item_model_name` String,
    `item_category_code` String,
    `item_category_name` String,
    `item_class_code` String,
    `item_class_name` String,
    `group_main_code` String,
    `group_main_name` String,
    `group_sub_code` String,
    `group_sub_name` String,
    `group_sub2_code` String,
    `group_sub2_name` String,
    `description` String,
    `status_cancel` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(r.raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(r.raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(r.raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    r.item_code_value AS item_code,
    JSONExtractString(r.raw_data, 'payload', 'after', 'barcode') AS barcode,
    JSONExtractString(r.raw_data, 'payload', 'after', 'item_name') AS item_name,
    JSONExtractString(r.raw_data, 'payload', 'after', 'unit_code') AS unit_code,
    '' AS unit_name,
    JSONExtractString(r.raw_data, 'payload', 'after', 'wh_code') AS wh_code,
    '' AS wh_name,
    JSONExtractString(r.raw_data, 'payload', 'after', 'shelf_code') AS shelf_code,
    '' AS shelf_name,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'qty') AS qty,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'price') AS price,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'discount_amount') AS discount_amount,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'sum_amount') AS sum_amount,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'sum_of_cost') AS sum_of_cost,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'average_cost') AS average_cost,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'stand_value') AS stand_value,
    JSONExtractFloat(r.raw_data, 'payload', 'after', 'divide_value') AS divide_value,
    multiIf(JSONExtractInt(r.raw_data, 'payload', 'after', 'tax_type') = 1, 'VAT', JSONExtractInt(r.raw_data, 'payload', 'after', 'tax_type') = 2, 'EXCEPTVAT', 'VAT') AS tax_type,
    ifNull(im.item_brand_code, '') AS item_brand_code,
    ifNull(im.item_brand_name, '') AS item_brand_name,
    JSONExtractString(r.raw_data, 'payload', 'after', 'ic_pattern') AS item_pattern_code,
    '' AS item_pattern_name,
    '' AS item_design_code,
    '' AS item_design_name,
    '' AS item_grade_code,
    '' AS item_grade_name,
    '' AS item_model_code,
    '' AS item_model_name,
    ifNull(im.item_category_code, '') AS item_category_code,
    ifNull(im.item_category_name, '') AS item_category_name,
    '' AS item_class_code,
    '' AS item_class_name,
    ifNull(im.group_main_code, '') AS group_main_code,
    ifNull(im.group_main_name, '') AS group_main_name,
    ifNull(im.group_sub_code, '') AS group_sub_code,
    ifNull(im.group_sub_name, '') AS group_sub_name,
    ifNull(im.group_sub2_code, '') AS group_sub2_code,
    ifNull(im.group_sub2_name, '') AS group_sub2_name,
    JSONExtractString(r.raw_data, 'payload', 'after', 'remark') AS description,
    if(JSONExtractInt(r.raw_data, 'payload', 'after', 'status') = 1, 'Cancel', '') AS status_cancel,
    r.branch_sync_value AS branch_sync,
    r.branch_sync_name_value AS branch_sync_name
FROM
(
    SELECT
        raw_data,
        _topic,
        multiIf(position(_topic, 'branch_000.') > 0, 'b000', position(_topic, 'branch_001.') > 0, 'b001', position(_topic, 'branch_002.') > 0, 'b002', position(_topic, 'branch_003.') > 0, 'b003', position(_topic, 'branch_004.') > 0, 'b004', position(_topic, 'branch_005.') > 0, 'b005', '') AS branch_sync_value,
        multiIf(position(_topic, 'branch_000.') > 0, 'บริษัท ช้าง สยาม กัมปนี จำกัด', position(_topic, 'branch_001.') > 0, 'บริษัท ช้างสยามรวย จำกัด', position(_topic, 'branch_002.') > 0, 'บริษัท ช้าง ทรัพย์ ทวี จำกัด', position(_topic, 'branch_003.') > 0, 'บริษัท ชาวทะเลเฮฮา จำกัด', position(_topic, 'branch_004.') > 0, 'บริษัท ดีจิงจัง 5665 จำกัด', position(_topic, 'branch_005.') > 0, 'บริษัท ฮอมฮัก จำกัด', '') AS branch_sync_name_value,
        JSONExtractString(raw_data, 'payload', 'after', 'item_code') AS item_code_value
    FROM datachangsiam.ic_trans_detail_raw
) AS r
LEFT JOIN datachangsiam.item_master AS im ON (im.branch_sync = r.branch_sync_value) AND (im.item_code = r.item_code_value)
WHERE (JSONExtractString(r.raw_data, 'payload', 'op') IN ('c', 'r')) AND (JSONExtractInt(r.raw_data, 'payload', 'after', 'trans_type') = 2);

