-- Generated by scripts/dump-cdc-clickhouse-schema.js
-- Database: datachangsiam

-- ap_ar_trans_queue (Kafka)
CREATE TABLE datachangsiam.ap_ar_trans_queue
(
    `raw_data` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:29092', kafka_topic_list = 'branch_000.public.ap_ar_trans,branch_001.public.ap_ar_trans,branch_002.public.ap_ar_trans,branch_003.public.ap_ar_trans,branch_004.public.ap_ar_trans,branch_005.public.ap_ar_trans', kafka_group_name = 'clickhouse_aparans_sync', kafka_format = 'JSONAsString', kafka_num_consumers = 1

-- ap_ar_trans_to_payment_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ap_ar_trans_to_payment_mv TO datachangsiam.payment_transaction
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `status_cancel` String,
    `doc_type` String,
    `pay_type` String,
    `debtor_creditor_type` String,
    `debtor_creditor_name` String,
    `total_amount` Float64,
    `other_charge_amount` Float64,
    `total_credit_charge` Float64,
    `total_net_amount` Float64,
    `cash_amount` Float64,
    `rounding_amount` Float64,
    `petty_cash_amount` Float64,
    `deposit_amount` Float64,
    `total_tax_at_pay` Float64,
    `cheque_amount` Float64,
    `transfer_amount` Float64,
    `card_amount` Float64,
    `coupon_amount` Float64,
    `point_amount` Float64,
    `discount_amount` Float64,
    `other_payment_amount` Float64,
    `wallet_amount` Float64,
    `total_amount_pay` Float64,
    `branch_code` String,
    `branch_name` String,
    `department_code` String,
    `department_name` String,
    `side_code` String,
    `side_name` String,
    `project_code` String,
    `project_name` String,
    `job_code` String,
    `job_name` String,
    `allocate_code` String,
    `allocate_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    if((JSONExtractString(raw_data, 'payload', 'after', 'is_cancel') IN ('true', '1')), 'Cancel', '') AS status_cancel,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_type') AS doc_type,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'trans_flag') = 19, 'out', (JSONExtractInt(raw_data, 'payload', 'after', 'trans_flag') IN (235, 239)), 'in', 'out') AS pay_type,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'trans_flag') = 19, 'SUPPLIER', (JSONExtractInt(raw_data, 'payload', 'after', 'trans_flag') IN (235, 239)), 'CUSTOMER', 'OTHER') AS debtor_creditor_type,
    JSONExtractString(raw_data, 'payload', 'after', 'cust_code') AS debtor_creditor_name,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_amount') AS total_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'other_charge_amount') AS other_charge_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_credit_charge') AS total_credit_charge,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_net_amount') AS total_net_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'cash_amount') AS cash_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'rounding_amount') AS rounding_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'petty_cash_amount') AS petty_cash_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'deposit_amount') AS deposit_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_tax_at_pay') AS total_tax_at_pay,
    JSONExtractFloat(raw_data, 'payload', 'after', 'cheque_amount') AS cheque_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'transfer_amount') AS transfer_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'card_amount') AS card_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'coupon_amount') AS coupon_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'point_amount') AS point_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'discount_amount') AS discount_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'other_payment_amount') AS other_payment_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'wallet_amount') AS wallet_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_amount_pay') AS total_amount_pay,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'department_code') AS department_code,
    '' AS department_name,
    JSONExtractString(raw_data, 'payload', 'after', 'side_code') AS side_code,
    '' AS side_name,
    JSONExtractString(raw_data, 'payload', 'after', 'project_code') AS project_code,
    '' AS project_name,
    JSONExtractString(raw_data, 'payload', 'after', 'job_code') AS job_code,
    '' AS job_name,
    JSONExtractString(raw_data, 'payload', 'after', 'allocate_code') AS allocate_code,
    '' AS allocate_name
FROM datachangsiam.ap_ar_trans_queue
WHERE JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r')

-- gl_journal_detail_queue (Kafka)
CREATE TABLE datachangsiam.gl_journal_detail_queue
(
    `raw_data` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:29092', kafka_topic_list = 'branch_000.public.gl_journal_detail,branch_001.public.gl_journal_detail,branch_002.public.gl_journal_detail,branch_003.public.gl_journal_detail,branch_004.public.gl_journal_detail,branch_005.public.gl_journal_detail', kafka_group_name = 'clickhouse_journal_sync', kafka_format = 'JSONAsString', kafka_num_consumers = 1

-- gl_journal_to_journal_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.gl_journal_to_journal_mv TO datachangsiam.journal_transaction_detail
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `period_number` String,
    `account_year` String,
    `book_code` String,
    `book_name` String,
    `account_code` String,
    `account_name` String,
    `debit` Float64,
    `credit` Float64,
    `account_type` String,
    `branch_code` String,
    `branch_name` String,
    `branch_sync` LowCardinality(String),
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(raw_data, 'payload', 'after', 'period_number') AS period_number,
    JSONExtractString(raw_data, 'payload', 'after', 'account_year') AS account_year,
    JSONExtractString(raw_data, 'payload', 'after', 'book_code') AS book_code,
    '' AS book_name,
    JSONExtractString(raw_data, 'payload', 'after', 'account_code') AS account_code,
    '' AS account_name,
    JSONExtractFloat(raw_data, 'payload', 'after', 'debit') AS debit,
    JSONExtractFloat(raw_data, 'payload', 'after', 'credit') AS credit,
    '' AS account_type,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.gl_journal_detail_queue
WHERE JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r')

-- ic_trans_detail_queue (Kafka)
CREATE TABLE datachangsiam.ic_trans_detail_queue
(
    `raw_data` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:29092', kafka_topic_list = 'branch_000.public.ic_trans_detail,branch_001.public.ic_trans_detail,branch_002.public.ic_trans_detail,branch_003.public.ic_trans_detail,branch_004.public.ic_trans_detail,branch_005.public.ic_trans_detail', kafka_group_name = 'clickhouse_ictransdetail_sync', kafka_format = 'JSONAsString', kafka_num_consumers = 1

-- ic_trans_detail_raw (MergeTree)
CREATE TABLE datachangsiam.ic_trans_detail_raw
(
    `raw_data` String,
    `_topic` String,
    `_inserted` DateTime DEFAULT now()
)
ENGINE = MergeTree
ORDER BY _inserted
TTL _inserted + toIntervalDay(3)
SETTINGS index_granularity = 8192

-- Columns for ic_trans_detail_raw
--   raw_data: String DEFAULT
--   _topic: String DEFAULT
--   _inserted: DateTime DEFAULT DEFAULT now()

-- ic_trans_detail_to_purchase_detail_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_detail_to_purchase_detail_mv TO datachangsiam.purchase_transaction_detail
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `branch_code` String,
    `branch_name` String,
    `item_code` String,
    `barcode` String,
    `item_name` String,
    `unit_code` String,
    `unit_name` String,
    `wh_code` String,
    `wh_name` String,
    `shelf_code` String,
    `shelf_name` String,
    `qty` Float64,
    `price` Float64,
    `discount_amount` Float64,
    `sum_amount` Float64,
    `sum_of_cost` Float64,
    `average_cost` Float64,
    `stand_value` Float64,
    `divide_value` Float64,
    `tax_type` String,
    `item_brand_code` String,
    `item_brand_name` String,
    `item_pattern_code` String,
    `item_pattern_name` String,
    `item_design_code` String,
    `item_design_name` String,
    `item_grade_code` String,
    `item_grade_name` String,
    `item_model_code` String,
    `item_model_name` String,
    `item_category_code` String,
    `item_category_name` String,
    `item_class_code` String,
    `item_class_name` String,
    `group_main_code` String,
    `group_main_name` String,
    `group_sub_code` String,
    `group_sub_name` String,
    `group_sub2_code` String,
    `group_sub2_name` String,
    `description` String,
    `status_cancel` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'item_code') AS item_code,
    JSONExtractString(raw_data, 'payload', 'after', 'barcode') AS barcode,
    JSONExtractString(raw_data, 'payload', 'after', 'item_name') AS item_name,
    JSONExtractString(raw_data, 'payload', 'after', 'unit_code') AS unit_code,
    '' AS unit_name,
    JSONExtractString(raw_data, 'payload', 'after', 'wh_code') AS wh_code,
    '' AS wh_name,
    JSONExtractString(raw_data, 'payload', 'after', 'shelf_code') AS shelf_code,
    '' AS shelf_name,
    JSONExtractFloat(raw_data, 'payload', 'after', 'qty') AS qty,
    JSONExtractFloat(raw_data, 'payload', 'after', 'price') AS price,
    JSONExtractFloat(raw_data, 'payload', 'after', 'discount_amount') AS discount_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_amount') AS sum_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_of_cost') AS sum_of_cost,
    JSONExtractFloat(raw_data, 'payload', 'after', 'average_cost') AS average_cost,
    JSONExtractFloat(raw_data, 'payload', 'after', 'stand_value') AS stand_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'divide_value') AS divide_value,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'tax_type') = 1, 'VAT', JSONExtractInt(raw_data, 'payload', 'after', 'tax_type') = 2, 'EXCEPTVAT', 'VAT') AS tax_type,
    '' AS item_brand_code,
    '' AS item_brand_name,
    '' AS item_pattern_code,
    '' AS item_pattern_name,
    '' AS item_design_code,
    '' AS item_design_name,
    '' AS item_grade_code,
    '' AS item_grade_name,
    '' AS item_model_code,
    '' AS item_model_name,
    '' AS item_category_code,
    '' AS item_category_name,
    '' AS item_class_code,
    '' AS item_class_name,
    '' AS group_main_code,
    '' AS group_main_name,
    '' AS group_sub_code,
    '' AS group_sub_name,
    '' AS group_sub2_code,
    '' AS group_sub2_name,
    JSONExtractString(raw_data, 'payload', 'after', 'remark') AS description,
    if(JSONExtractInt(raw_data, 'payload', 'after', 'status') = 1, 'Cancel', '') AS status_cancel,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_detail_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 1) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'))

-- ic_trans_detail_to_raw_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_detail_to_raw_mv TO datachangsiam.ic_trans_detail_raw
(
    `raw_data` String,
    `_topic` LowCardinality(String)
)
AS SELECT
    raw_data,
    _topic
FROM datachangsiam.ic_trans_detail_queue

-- ic_trans_detail_to_sale_detail_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_detail_to_sale_detail_mv TO datachangsiam.saleinvoice_transaction_detail
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `branch_code` String,
    `branch_name` String,
    `item_code` String,
    `barcode` String,
    `item_name` String,
    `unit_code` String,
    `unit_name` String,
    `wh_code` String,
    `wh_name` String,
    `shelf_code` String,
    `shelf_name` String,
    `qty` Float64,
    `price` Float64,
    `discount_amount` Float64,
    `sum_amount` Float64,
    `sum_of_cost` Float64,
    `average_cost` Float64,
    `stand_value` Float64,
    `divide_value` Float64,
    `tax_type` String,
    `item_brand_code` String,
    `item_brand_name` String,
    `item_pattern_code` String,
    `item_pattern_name` String,
    `item_design_code` String,
    `item_design_name` String,
    `item_grade_code` String,
    `item_grade_name` String,
    `item_model_code` String,
    `item_model_name` String,
    `item_category_code` String,
    `item_category_name` String,
    `item_class_code` String,
    `item_class_name` String,
    `group_main_code` String,
    `group_main_name` String,
    `group_sub_code` String,
    `group_sub_name` String,
    `group_sub2_code` String,
    `group_sub2_name` String,
    `description` String,
    `status_cancel` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'item_code') AS item_code,
    JSONExtractString(raw_data, 'payload', 'after', 'barcode') AS barcode,
    JSONExtractString(raw_data, 'payload', 'after', 'item_name') AS item_name,
    JSONExtractString(raw_data, 'payload', 'after', 'unit_code') AS unit_code,
    '' AS unit_name,
    JSONExtractString(raw_data, 'payload', 'after', 'wh_code') AS wh_code,
    '' AS wh_name,
    JSONExtractString(raw_data, 'payload', 'after', 'shelf_code') AS shelf_code,
    '' AS shelf_name,
    JSONExtractFloat(raw_data, 'payload', 'after', 'qty') AS qty,
    JSONExtractFloat(raw_data, 'payload', 'after', 'price') AS price,
    JSONExtractFloat(raw_data, 'payload', 'after', 'discount_amount') AS discount_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_amount') AS sum_amount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_of_cost') AS sum_of_cost,
    JSONExtractFloat(raw_data, 'payload', 'after', 'average_cost') AS average_cost,
    JSONExtractFloat(raw_data, 'payload', 'after', 'stand_value') AS stand_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'divide_value') AS divide_value,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'tax_type') = 1, 'VAT', JSONExtractInt(raw_data, 'payload', 'after', 'tax_type') = 2, 'EXCEPTVAT', 'VAT') AS tax_type,
    '' AS item_brand_code,
    '' AS item_brand_name,
    '' AS item_pattern_code,
    '' AS item_pattern_name,
    '' AS item_design_code,
    '' AS item_design_name,
    '' AS item_grade_code,
    '' AS item_grade_name,
    '' AS item_model_code,
    '' AS item_model_name,
    '' AS item_category_code,
    '' AS item_category_name,
    '' AS item_class_code,
    '' AS item_class_name,
    '' AS group_main_code,
    '' AS group_main_name,
    '' AS group_sub_code,
    '' AS group_sub_name,
    '' AS group_sub2_code,
    '' AS group_sub2_name,
    JSONExtractString(raw_data, 'payload', 'after', 'remark') AS description,
    if(JSONExtractInt(raw_data, 'payload', 'after', 'status') = 1, 'Cancel', '') AS status_cancel,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_detail_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 2) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'))

-- ic_trans_detail_to_stock_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_detail_to_stock_mv TO datachangsiam.stock_transaction
(
    `item_code` String,
    `item_name` String,
    `doc_datetime` DateTime,
    `doc_no` String,
    `doc_type` String,
    `ic_unit_code` String,
    `ic_unit_name` String,
    `wh_code` String,
    `wh_name` String,
    `shelf_code` String,
    `shelf_name` String,
    `calc_type` String,
    `qty` Float64,
    `cost` Float64,
    `amount` Float64,
    `item_brand_code` String,
    `item_brand_name` String,
    `item_pattern_code` String,
    `item_pattern_name` String,
    `item_design_code` String,
    `item_design_name` String,
    `item_grade_code` String,
    `item_grade_name` String,
    `item_model_code` String,
    `item_model_name` String,
    `item_category_code` String,
    `item_category_name` String,
    `item_class_code` String,
    `item_class_name` String,
    `group_main_code` String,
    `group_main_name` String,
    `group_sub_code` String,
    `group_sub_name` String,
    `group_sub2_code` String,
    `group_sub2_name` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    JSONExtractString(raw_data, 'payload', 'after', 'item_code') AS item_code,
    JSONExtractString(raw_data, 'payload', 'after', 'item_name') AS item_name,
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    '' AS doc_type,
    JSONExtractString(raw_data, 'payload', 'after', 'unit_code') AS ic_unit_code,
    '' AS ic_unit_name,
    JSONExtractString(raw_data, 'payload', 'after', 'wh_code') AS wh_code,
    '' AS wh_name,
    JSONExtractString(raw_data, 'payload', 'after', 'shelf_code') AS shelf_code,
    '' AS shelf_name,
    '' AS calc_type,
    JSONExtractFloat(raw_data, 'payload', 'after', 'qty') AS qty,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_of_cost') AS cost,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_amount') AS amount,
    '' AS item_brand_code,
    '' AS item_brand_name,
    '' AS item_pattern_code,
    '' AS item_pattern_name,
    '' AS item_design_code,
    '' AS item_design_name,
    '' AS item_grade_code,
    '' AS item_grade_name,
    '' AS item_model_code,
    '' AS item_model_name,
    '' AS item_category_code,
    '' AS item_category_name,
    '' AS item_class_code,
    '' AS item_class_name,
    '' AS group_main_code,
    '' AS group_main_name,
    '' AS group_sub_code,
    '' AS group_sub_name,
    '' AS group_sub2_code,
    '' AS group_sub2_name,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_detail_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 3) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'))

-- ic_trans_queue (Kafka)
CREATE TABLE datachangsiam.ic_trans_queue
(
    `raw_data` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:29092', kafka_topic_list = 'branch_000.public.ic_trans,branch_001.public.ic_trans,branch_002.public.ic_trans,branch_003.public.ic_trans,branch_004.public.ic_trans,branch_005.public.ic_trans', kafka_group_name = 'clickhouse_ictrans_sync', kafka_format = 'JSONAsString', kafka_num_consumers = 1

-- ic_trans_raw (MergeTree)
CREATE TABLE datachangsiam.ic_trans_raw
(
    `raw_data` String,
    `_topic` String,
    `_inserted` DateTime DEFAULT now()
)
ENGINE = MergeTree
ORDER BY _inserted
TTL _inserted + toIntervalDay(3)
SETTINGS index_granularity = 8192

-- Columns for ic_trans_raw
--   raw_data: String DEFAULT
--   _topic: String DEFAULT
--   _inserted: DateTime DEFAULT DEFAULT now()

-- ic_trans_to_purchase_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_to_purchase_mv TO datachangsiam.purchase_transaction
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `status_cancel` String,
    `creator_code` String,
    `creator_name` String,
    `pos_id` String,
    `supplier_code` String,
    `supplier_name` String,
    `sale_code` String,
    `sale_name` String,
    `doc_type` String,
    `due_date` DateTime,
    `sum_point` Float64,
    `total_value` Float64,
    `total_discount` Float64,
    `total_before_vat` Float64,
    `total_vat_value` Float64,
    `total_after_vat` Float64,
    `total_except_vat` Float64,
    `total_amount` Float64,
    `remark` String,
    `branch_code` String,
    `branch_name` String,
    `department_code` String,
    `department_name` String,
    `side_code` String,
    `side_name` String,
    `project_code` String,
    `project_name` String,
    `job_code` String,
    `job_name` String,
    `allocate_code` String,
    `allocate_name` String,
    `billing_no_array` String,
    `sum_pay_money` Float64,
    `status_payment` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    if((JSONExtractString(raw_data, 'payload', 'after', 'is_cancel') IN ('true', '1')), 'Cancel', '') AS status_cancel,
    JSONExtractString(raw_data, 'payload', 'after', 'creator_code') AS creator_code,
    '' AS creator_name,
    JSONExtractString(raw_data, 'payload', 'after', 'pos_id') AS pos_id,
    JSONExtractString(raw_data, 'payload', 'after', 'cust_code') AS supplier_code,
    '' AS supplier_name,
    JSONExtractString(raw_data, 'payload', 'after', 'sale_code') AS sale_code,
    '' AS sale_name,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_type') AS doc_type,
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'due_date'))) AS due_date,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_point') AS sum_point,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_value') AS total_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_discount') AS total_discount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_before_vat') AS total_before_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_vat_value') AS total_vat_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_after_vat') AS total_after_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_except_vat') AS total_except_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_amount') AS total_amount,
    JSONExtractString(raw_data, 'payload', 'after', 'remark') AS remark,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'department_code') AS department_code,
    '' AS department_name,
    JSONExtractString(raw_data, 'payload', 'after', 'side_code') AS side_code,
    '' AS side_name,
    JSONExtractString(raw_data, 'payload', 'after', 'project_code') AS project_code,
    '' AS project_name,
    JSONExtractString(raw_data, 'payload', 'after', 'job_code') AS job_code,
    '' AS job_name,
    JSONExtractString(raw_data, 'payload', 'after', 'allocate_code') AS allocate_code,
    '' AS allocate_name,
    '' AS billing_no_array,
    JSONExtractFloat(raw_data, 'payload', 'after', 'pay_amount') AS sum_pay_money,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 0, 'Outstanding', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 1, 'Partially Paid', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 2, 'Fully Paid', '') AS status_payment,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 1) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'))

-- ic_trans_to_raw_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_to_raw_mv TO datachangsiam.ic_trans_raw
(
    `raw_data` String,
    `_topic` LowCardinality(String)
)
AS SELECT
    raw_data,
    _topic
FROM datachangsiam.ic_trans_queue

-- ic_trans_to_sale_mv (MaterializedView)
CREATE MATERIALIZED VIEW datachangsiam.ic_trans_to_sale_mv TO datachangsiam.saleinvoice_transaction
(
    `doc_datetime` DateTime,
    `doc_no` String,
    `creator_code` String,
    `creator_name` String,
    `status_cancel` String,
    `pos_id` String,
    `customer_code` String,
    `customer_name` String,
    `sale_code` String,
    `sale_name` String,
    `doc_type` String,
    `due_date` DateTime,
    `sum_point` Float64,
    `total_value` Float64,
    `total_discount` Float64,
    `total_before_vat` Float64,
    `total_vat_value` Float64,
    `total_after_vat` Float64,
    `total_except_vat` Float64,
    `total_amount` Float64,
    `remark` String,
    `branch_code` String,
    `branch_name` String,
    `department_code` String,
    `department_name` String,
    `side_code` String,
    `side_name` String,
    `project_code` String,
    `project_name` String,
    `job_code` String,
    `job_name` String,
    `allocate_code` String,
    `allocate_name` String,
    `billing_no_array` String,
    `sum_pay_money` Float64,
    `status_payment` String,
    `branch_sync` String,
    `branch_sync_name` String
)
AS SELECT
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'doc_date'))) AS doc_datetime,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_no') AS doc_no,
    JSONExtractString(raw_data, 'payload', 'after', 'creator_code') AS creator_code,
    '' AS creator_name,
    if((JSONExtractString(raw_data, 'payload', 'after', 'is_cancel') IN ('true', '1')), 'Cancel', '') AS status_cancel,
    JSONExtractString(raw_data, 'payload', 'after', 'pos_id') AS pos_id,
    JSONExtractString(raw_data, 'payload', 'after', 'cust_code') AS customer_code,
    '' AS customer_name,
    JSONExtractString(raw_data, 'payload', 'after', 'sale_code') AS sale_code,
    '' AS sale_name,
    JSONExtractString(raw_data, 'payload', 'after', 'doc_type') AS doc_type,
    toDateTime(toDate(JSONExtractInt(raw_data, 'payload', 'after', 'due_date'))) AS due_date,
    JSONExtractFloat(raw_data, 'payload', 'after', 'sum_point') AS sum_point,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_value') AS total_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_discount') AS total_discount,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_before_vat') AS total_before_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_vat_value') AS total_vat_value,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_after_vat') AS total_after_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_except_vat') AS total_except_vat,
    JSONExtractFloat(raw_data, 'payload', 'after', 'total_amount') AS total_amount,
    JSONExtractString(raw_data, 'payload', 'after', 'remark') AS remark,
    JSONExtractString(raw_data, 'payload', 'after', 'branch_code') AS branch_code,
    '' AS branch_name,
    JSONExtractString(raw_data, 'payload', 'after', 'department_code') AS department_code,
    '' AS department_name,
    JSONExtractString(raw_data, 'payload', 'after', 'side_code') AS side_code,
    '' AS side_name,
    JSONExtractString(raw_data, 'payload', 'after', 'project_code') AS project_code,
    '' AS project_name,
    JSONExtractString(raw_data, 'payload', 'after', 'job_code') AS job_code,
    '' AS job_name,
    JSONExtractString(raw_data, 'payload', 'after', 'allocate_code') AS allocate_code,
    '' AS allocate_name,
    '' AS billing_no_array,
    JSONExtractFloat(raw_data, 'payload', 'after', 'pay_amount') AS sum_pay_money,
    multiIf(JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 0, 'Outstanding', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 1, 'Partially Paid', JSONExtractInt(raw_data, 'payload', 'after', 'last_status') = 2, 'Fully Paid', '') AS status_payment,
    concat('b', extract(_topic, 'branch_(\\d+)')) AS branch_sync,
    '' AS branch_sync_name
FROM datachangsiam.ic_trans_raw
WHERE (JSONExtractInt(raw_data, 'payload', 'after', 'trans_type') = 2) AND (JSONExtractString(raw_data, 'payload', 'op') IN ('c', 'u', 'r'))

-- journal_transaction_detail (MergeTree)
CREATE TABLE datachangsiam.journal_transaction_detail
(
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `period_number` String COMMENT 'งวดบัญชี',
    `account_year` String COMMENT 'ปีภาษี',
    `book_code` String COMMENT 'รหัสสมุดบัญชี',
    `book_name` String COMMENT 'ชื่อสมุดบัญชี',
    `account_code` String COMMENT 'รหัสผังบัญชี',
    `account_name` String COMMENT 'ชื่อผังบัญชี',
    `debit` Float64 COMMENT 'ยอดเดบิต',
    `credit` Float64 COMMENT 'ยอดเครดิต',
    `account_type` String COMMENT 'หมวดบัญชี ASSETS=สินทรัพย์, LIABILITIES=หนี้สิน, EQUITY=ทุน, INCOME=รายได้, EXPENSES=ค่าใช้จ่าย',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY substring(doc_no, 1, 6)
PRIMARY KEY (doc_no, branch_sync, branch_sync_name)
ORDER BY (doc_no, branch_sync, branch_sync_name, doc_datetime)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'รายละเอียดการบันทึกบัญชี'

-- Columns for journal_transaction_detail
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   period_number: String DEFAULT
--   account_year: String DEFAULT
--   book_code: String DEFAULT
--   book_name: String DEFAULT
--   account_code: String DEFAULT
--   account_name: String DEFAULT
--   debit: Float64 DEFAULT
--   credit: Float64 DEFAULT
--   account_type: String DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

-- payment_transaction (MergeTree)
CREATE TABLE datachangsiam.payment_transaction
(
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String,
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `status_cancel` String COMMENT 'สถานะยกเลิก Cancel=ยกเลิก',
    `doc_type` String COMMENT 'ประเภทเอกสาร',
    `pay_type` String COMMENT 'ประเภทการรับ/จ่ายเงิน in=รับเงิน , out=จ่ายเงิน',
    `debtor_creditor_type` String COMMENT 'ประเภท ลูกหนี้/เจ้าหนี้ CUSTOMER=ลูกหนี้/ลูกค้า , SUPPLIER=เจ้าหนี้ , OTHER=อื่นๆ',
    `debtor_creditor_name` String COMMENT 'ชื่อ ลูกหนี้/เจ้าหนี้',
    `total_amount` Float64 COMMENT 'รวมยอดเงินตามบิล',
    `other_charge_amount` Float64 COMMENT 'รับ/จ่ายอื่นๆ เพิ่มจากยอดบิล',
    `total_credit_charge` Float64 COMMENT 'ยอดรวมค่า charge บัตรเครดิต',
    `total_net_amount` Float64 COMMENT 'ยอดรวมสุทธิที่ต้องรับ/จ่าย',
    `cash_amount` Float64 COMMENT 'ยอดเงินสด',
    `rounding_amount` Float64 COMMENT 'ยอดปัดเศษ',
    `petty_cash_amount` Float64 COMMENT 'ยอดเงินสดย่อย',
    `deposit_amount` Float64 COMMENT 'ยอดเงินล่วงหน้า',
    `total_tax_at_pay` Float64 COMMENT 'ยอดภาษีหัก ณ ที่จ่าย',
    `cheque_amount` Float64 COMMENT 'ยอดเช็ค',
    `transfer_amount` Float64 COMMENT 'ยอดเงินโอน',
    `card_amount` Float64 COMMENT 'ยอดบัตรเครดิต',
    `coupon_amount` Float64 COMMENT 'ยอดคูปอง',
    `point_amount` Float64 COMMENT 'ยอดแต้มที่ใช้เป็นส่วนลด',
    `discount_amount` Float64 COMMENT 'ยอดส่วนลดการชำระเงิน',
    `other_payment_amount` Float64 COMMENT 'ยอดชำระอื่นๆ',
    `wallet_amount` Float64 COMMENT 'ยอดที่รับ/จ่ายผ่าน Wallet',
    `total_amount_pay` Float64 COMMENT 'รวมยอดรับเงิน/จ่ายเงิน',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `department_code` String COMMENT 'รหัสแผนก',
    `department_name` String COMMENT 'ชื่อแผนก',
    `side_code` String COMMENT 'รหัสฝ่าย',
    `side_name` String COMMENT 'ชื่อฝ่าย',
    `project_code` String COMMENT 'รหัสโครงการ',
    `project_name` String COMMENT 'ชื่อโครงการ',
    `job_code` String COMMENT 'รหัสงาน',
    `job_name` String COMMENT 'ชื่องาน',
    `allocate_code` String COMMENT 'รหัสการจัดสรร',
    `allocate_name` String COMMENT 'ชื่อการจัดสรร'
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(doc_datetime)
PRIMARY KEY (branch_sync, doc_no)
ORDER BY (branch_sync, doc_no, doc_datetime)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'รายละเอียดการชำระ'

-- Columns for payment_transaction
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   status_cancel: String DEFAULT
--   doc_type: String DEFAULT
--   pay_type: String DEFAULT
--   debtor_creditor_type: String DEFAULT
--   debtor_creditor_name: String DEFAULT
--   total_amount: Float64 DEFAULT
--   other_charge_amount: Float64 DEFAULT
--   total_credit_charge: Float64 DEFAULT
--   total_net_amount: Float64 DEFAULT
--   cash_amount: Float64 DEFAULT
--   rounding_amount: Float64 DEFAULT
--   petty_cash_amount: Float64 DEFAULT
--   deposit_amount: Float64 DEFAULT
--   total_tax_at_pay: Float64 DEFAULT
--   cheque_amount: Float64 DEFAULT
--   transfer_amount: Float64 DEFAULT
--   card_amount: Float64 DEFAULT
--   coupon_amount: Float64 DEFAULT
--   point_amount: Float64 DEFAULT
--   discount_amount: Float64 DEFAULT
--   other_payment_amount: Float64 DEFAULT
--   wallet_amount: Float64 DEFAULT
--   total_amount_pay: Float64 DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   department_code: String DEFAULT
--   department_name: String DEFAULT
--   side_code: String DEFAULT
--   side_name: String DEFAULT
--   project_code: String DEFAULT
--   project_name: String DEFAULT
--   job_code: String DEFAULT
--   job_name: String DEFAULT
--   allocate_code: String DEFAULT
--   allocate_name: String DEFAULT

-- purchase_transaction (MergeTree)
CREATE TABLE datachangsiam.purchase_transaction
(
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `status_cancel` String COMMENT 'สถานะยกเลิก Cancel=ยกเลิก',
    `creator_code` String COMMENT 'รหัสผู้สร้างเอกสาร',
    `creator_name` String COMMENT 'ชื่อผู้สร้างเอกสาร',
    `pos_id` String COMMENT 'หมายเลขเครื่อง POS ถ้ามีแปลว่ามาจากขาย POS',
    `supplier_code` String COMMENT 'รหัสเจ้าหนี้',
    `supplier_name` String COMMENT 'ชื่อเจ้าหนี้',
    `sale_code` String COMMENT 'รหัสพนักงานขาย',
    `sale_name` String COMMENT 'ชื่อพนักงานขาย',
    `doc_type` String COMMENT 'ประเภทเอกสาร CREDIT=เงินเชื่อ , CASH=เงินสด',
    `due_date` DateTime COMMENT 'วันที่ครบกำหนด',
    `sum_point` Float64 COMMENT 'แต้ม',
    `total_value` Float64 COMMENT 'มูลค่าสินค้า',
    `total_discount` Float64 COMMENT 'มูลค่าส่วนลด',
    `total_before_vat` Float64 COMMENT 'ยอดก่อนภาษี',
    `total_vat_value` Float64 COMMENT 'ภาษีมูลค่าเพิ่ม',
    `total_after_vat` Float64 COMMENT 'มูลค่าหลังคิดภาษี',
    `total_except_vat` Float64 COMMENT 'มูลค่ายกเว้นภาษี',
    `total_amount` Float64 COMMENT 'มูลค่าสุทธิ',
    `remark` String COMMENT 'หมายเหตุ ทั้งหมด',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `department_code` String COMMENT 'รหัสแผนก',
    `department_name` String COMMENT 'ชื่อแผนก',
    `side_code` String COMMENT 'รหัสฝ่าย',
    `side_name` String COMMENT 'ชื่อฝ่าย',
    `project_code` String COMMENT 'รหัสโครงการ',
    `project_name` String COMMENT 'ชื่อโครงการ',
    `job_code` String COMMENT 'รหัสงาน',
    `job_name` String COMMENT 'ชื่องาน',
    `allocate_code` String COMMENT 'รหัสการจัดสรร',
    `allocate_name` String COMMENT 'ชื่อการจัดสรร',
    `billing_no_array` String COMMENT 'list เอกสารรับชำระ (รูปแบบ Json)',
    `sum_pay_money` Float64 COMMENT 'มูลค่ารับชำระ (กรณีขายเงินเชื่อ)',
    `status_payment` String COMMENT 'สถานะค้างชำระ Outstanding=ค้างชำระ , Partially Paid=ชำระบางส่วน , Fully Paid=ชำระครบแล้ว',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(doc_datetime)
PRIMARY KEY (doc_no, branch_sync, branch_sync_name)
ORDER BY (doc_no, branch_sync, branch_sync_name, doc_datetime)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'เอกสารซื้อ'

-- Columns for purchase_transaction
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   status_cancel: String DEFAULT
--   creator_code: String DEFAULT
--   creator_name: String DEFAULT
--   pos_id: String DEFAULT
--   supplier_code: String DEFAULT
--   supplier_name: String DEFAULT
--   sale_code: String DEFAULT
--   sale_name: String DEFAULT
--   doc_type: String DEFAULT
--   due_date: DateTime DEFAULT
--   sum_point: Float64 DEFAULT
--   total_value: Float64 DEFAULT
--   total_discount: Float64 DEFAULT
--   total_before_vat: Float64 DEFAULT
--   total_vat_value: Float64 DEFAULT
--   total_after_vat: Float64 DEFAULT
--   total_except_vat: Float64 DEFAULT
--   total_amount: Float64 DEFAULT
--   remark: String DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   department_code: String DEFAULT
--   department_name: String DEFAULT
--   side_code: String DEFAULT
--   side_name: String DEFAULT
--   project_code: String DEFAULT
--   project_name: String DEFAULT
--   job_code: String DEFAULT
--   job_name: String DEFAULT
--   allocate_code: String DEFAULT
--   allocate_name: String DEFAULT
--   billing_no_array: String DEFAULT
--   sum_pay_money: Float64 DEFAULT
--   status_payment: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

-- purchase_transaction_detail (MergeTree)
CREATE TABLE datachangsiam.purchase_transaction_detail
(
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `item_code` String COMMENT 'รหัสสินค้า',
    `barcode` String COMMENT 'บาร์โค้ด',
    `item_name` String COMMENT 'ชื่อสินค้า',
    `unit_code` String COMMENT 'รหัสหน่วยนับ',
    `unit_name` String COMMENT 'ชื่อหน่วยนับ',
    `wh_code` String COMMENT 'รหัสคลัง',
    `wh_name` String COMMENT 'ชื่อคลัง',
    `shelf_code` String COMMENT 'รหัสที่เก็บ',
    `shelf_name` String COMMENT 'ชื่อที่เก็บ',
    `qty` Float64 COMMENT 'จำนวน',
    `price` Float64 COMMENT 'ราคา',
    `discount_amount` Float64 COMMENT 'มูลค่าส่วนลด',
    `sum_amount` Float64 COMMENT 'มูลค่าสินค้า',
    `sum_of_cost` Float64 COMMENT 'มูลค่าต้นทุน',
    `average_cost` Float64 COMMENT 'ต้นทุนเฉลี่ย',
    `stand_value` Float64 COMMENT 'ตัวตั้ง',
    `divide_value` Float64 COMMENT 'ตัวหาร',
    `tax_type` String COMMENT 'ประเภทภาษี VAT=สินค้ามีภาษี , EXCEPTVAT=ยกเว้นภาษี',
    `item_brand_code` String COMMENT 'รหัสยี่ห้อสินค้า',
    `item_brand_name` String COMMENT 'ชื่อยี่ห้อสินค้า',
    `item_pattern_code` String COMMENT 'รหัสรูปแบบสินค้า',
    `item_pattern_name` String COMMENT 'ชื่อรูปแบบสินค้า',
    `item_design_code` String COMMENT 'รหัสรูปทรงสินค้า',
    `item_design_name` String COMMENT 'ชื่อรูปทรงสินค้า',
    `item_grade_code` String COMMENT 'รหัสเกรดสินค้า',
    `item_grade_name` String COMMENT 'ชื่อเกรดสินค้า',
    `item_model_code` String COMMENT 'รหัสรุ่นสินค้า',
    `item_model_name` String COMMENT 'ชื่อรุ่นสินค้า',
    `item_category_code` String COMMENT 'รหัสหมวดสินค้า',
    `item_category_name` String COMMENT 'ชื่อหมวดสินค้า',
    `item_class_code` String COMMENT 'รหัสระดับสินค้า',
    `item_class_name` String COMMENT 'ชื่อระดับสินค้า',
    `group_main_code` String COMMENT 'รหัสกลุ่มหลัก',
    `group_main_name` String COMMENT 'ชื่อกลุ่มหลัก',
    `group_sub_code` String COMMENT 'รหัสกลุ่มย่อย',
    `group_sub_name` String COMMENT 'ชื่อกลุ่มย่อย',
    `group_sub2_code` String COMMENT 'รหัสกลุ่มย่อย2',
    `group_sub2_name` String COMMENT 'ชื่อกลุ่มย่อย2',
    `description` String COMMENT 'รายละเอียด',
    `status_cancel` String COMMENT 'สถานะยกเลิก Cancel=ยกเลิก',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY toYear(doc_datetime)
PRIMARY KEY (doc_no, branch_sync, branch_sync_name)
ORDER BY (doc_no, branch_sync, branch_sync_name, doc_datetime)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'รายละเอียดเอกสารซื้อ'

-- Columns for purchase_transaction_detail
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   item_code: String DEFAULT
--   barcode: String DEFAULT
--   item_name: String DEFAULT
--   unit_code: String DEFAULT
--   unit_name: String DEFAULT
--   wh_code: String DEFAULT
--   wh_name: String DEFAULT
--   shelf_code: String DEFAULT
--   shelf_name: String DEFAULT
--   qty: Float64 DEFAULT
--   price: Float64 DEFAULT
--   discount_amount: Float64 DEFAULT
--   sum_amount: Float64 DEFAULT
--   sum_of_cost: Float64 DEFAULT
--   average_cost: Float64 DEFAULT
--   stand_value: Float64 DEFAULT
--   divide_value: Float64 DEFAULT
--   tax_type: String DEFAULT
--   item_brand_code: String DEFAULT
--   item_brand_name: String DEFAULT
--   item_pattern_code: String DEFAULT
--   item_pattern_name: String DEFAULT
--   item_design_code: String DEFAULT
--   item_design_name: String DEFAULT
--   item_grade_code: String DEFAULT
--   item_grade_name: String DEFAULT
--   item_model_code: String DEFAULT
--   item_model_name: String DEFAULT
--   item_category_code: String DEFAULT
--   item_category_name: String DEFAULT
--   item_class_code: String DEFAULT
--   item_class_name: String DEFAULT
--   group_main_code: String DEFAULT
--   group_main_name: String DEFAULT
--   group_sub_code: String DEFAULT
--   group_sub_name: String DEFAULT
--   group_sub2_code: String DEFAULT
--   group_sub2_name: String DEFAULT
--   description: String DEFAULT
--   status_cancel: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

-- saleinvoice_transaction (MergeTree)
CREATE TABLE datachangsiam.saleinvoice_transaction
(
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `creator_code` String COMMENT 'ผู้สร้างเอกสาร',
    `creator_name` String COMMENT 'ผู้สร้างเอกสาร',
    `status_cancel` String COMMENT 'สถานะยกเลิก Cancel=ยกเลิก',
    `pos_id` String COMMENT 'หมายเลขเครื่อง POS ถ้ามีแปลว่ามาจากขาย POS',
    `customer_code` String COMMENT 'รหัสลูกหนี้/ลูกค้า, ถ้าเป็นค่าว่าง คือลูกค้าทั่วไป',
    `customer_name` String COMMENT 'ชื่อลูกหนี้/ลูกค้า, ถ้าเป็นค่าว่าง คือลูกค้าทั่วไป',
    `sale_code` String COMMENT 'รหัสพนักงานขาย',
    `sale_name` String COMMENT 'ชื่อพนักงานขาย',
    `doc_type` String COMMENT 'ประเภทเอกสาร CREDIT=เงินเชื่อ, CASH=เงินสด',
    `due_date` DateTime COMMENT 'วันที่ครบกำหนด',
    `sum_point` Float64 COMMENT 'แต้ม',
    `total_value` Float64 COMMENT 'มูลค่าสินค้า',
    `total_discount` Float64 COMMENT 'มูลค่าส่วนลด',
    `total_before_vat` Float64 COMMENT 'ยอดก่อนภาษี',
    `total_vat_value` Float64 COMMENT 'ภาษีมูลค่าเพิ่ม',
    `total_after_vat` Float64 COMMENT 'มูลค่าหลังคิดภาษี',
    `total_except_vat` Float64 COMMENT 'มูลค่ายกเว้นภาษี',
    `total_amount` Float64 COMMENT 'มูลค่าสุทธิ',
    `remark` String COMMENT 'หมายเหตุ ทั้งหมด',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `department_code` String COMMENT 'รหัสแผนก',
    `department_name` String COMMENT 'ชื่อแผนก',
    `side_code` String COMMENT 'รหัสฝ่าย',
    `side_name` String COMMENT 'ชื่อฝ่าย',
    `project_code` String COMMENT 'รหัสโครงการ',
    `project_name` String COMMENT 'ชื่อโครงการ',
    `job_code` String COMMENT 'รหัสงาน',
    `job_name` String COMMENT 'ชื่องาน',
    `allocate_code` String COMMENT 'รหัสการจัดสรร',
    `allocate_name` String COMMENT 'ชื่อการจัดสรร',
    `billing_no_array` String COMMENT 'list เอกสารรับชำระ (รูปแบบ Json)',
    `sum_pay_money` Float64 COMMENT 'มูลค่ารับชำระ (กรณีขายเงินเชื่อ)',
    `status_payment` String COMMENT 'สถานะค้างชำระ Outstanding=ค้างชำระ, Partially Paid=ชำระบางส่วน, Fully Paid=ชำระครบแล้ว',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY toYear(doc_datetime)
PRIMARY KEY (doc_no, branch_sync, branch_sync_name)
ORDER BY (doc_no, branch_sync, branch_sync_name, doc_datetime)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'เอกสารขาย'

-- Columns for saleinvoice_transaction
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   creator_code: String DEFAULT
--   creator_name: String DEFAULT
--   status_cancel: String DEFAULT
--   pos_id: String DEFAULT
--   customer_code: String DEFAULT
--   customer_name: String DEFAULT
--   sale_code: String DEFAULT
--   sale_name: String DEFAULT
--   doc_type: String DEFAULT
--   due_date: DateTime DEFAULT
--   sum_point: Float64 DEFAULT
--   total_value: Float64 DEFAULT
--   total_discount: Float64 DEFAULT
--   total_before_vat: Float64 DEFAULT
--   total_vat_value: Float64 DEFAULT
--   total_after_vat: Float64 DEFAULT
--   total_except_vat: Float64 DEFAULT
--   total_amount: Float64 DEFAULT
--   remark: String DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   department_code: String DEFAULT
--   department_name: String DEFAULT
--   side_code: String DEFAULT
--   side_name: String DEFAULT
--   project_code: String DEFAULT
--   project_name: String DEFAULT
--   job_code: String DEFAULT
--   job_name: String DEFAULT
--   allocate_code: String DEFAULT
--   allocate_name: String DEFAULT
--   billing_no_array: String DEFAULT
--   sum_pay_money: Float64 DEFAULT
--   status_payment: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

-- saleinvoice_transaction_detail (MergeTree)
CREATE TABLE datachangsiam.saleinvoice_transaction_detail
(
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `branch_code` String COMMENT 'รหัสสาขา',
    `branch_name` String COMMENT 'ชื่อสาขา',
    `item_code` String COMMENT 'รหัสสินค้า',
    `barcode` String COMMENT 'บาร์โค้ด',
    `item_name` String COMMENT 'ชื่อสินค้า',
    `unit_code` String COMMENT 'รหัสหน่วยนับ',
    `unit_name` String COMMENT 'ชื่อหน่วยนับ',
    `wh_code` String COMMENT 'รหัสคลัง',
    `wh_name` String COMMENT 'ชื่อคลัง',
    `shelf_code` String COMMENT 'รหัสที่เก็บ',
    `shelf_name` String COMMENT 'ชื่อที่เก็บ',
    `qty` Float64 COMMENT 'จำนวน',
    `price` Float64 COMMENT 'ราคา',
    `discount_amount` Float64 COMMENT 'มูลค่าส่วนลด',
    `sum_amount` Float64 COMMENT 'มูลค่าสินค้า',
    `sum_of_cost` Float64 COMMENT 'มูลค่าต้นทุน',
    `average_cost` Float64 COMMENT 'ต้นทุนเฉลี่ย',
    `stand_value` Float64 COMMENT 'ตัวตั้ง',
    `divide_value` Float64 COMMENT 'ตัวหาร',
    `tax_type` String COMMENT 'ประเภทภาษี VAT=สินค้ามีภาษี, EXCEPTVAT=ยกเว้นภาษี',
    `item_brand_code` String COMMENT 'รหัสยี่ห้อสินค้า',
    `item_brand_name` String COMMENT 'ชื่อยี่ห้อสินค้า',
    `item_pattern_code` String COMMENT 'รหัสรูปแบบสินค้า',
    `item_pattern_name` String COMMENT 'ชื่อรูปแบบสินค้า',
    `item_design_code` String COMMENT 'รหัสรูปทรงสินค้า',
    `item_design_name` String COMMENT 'ชื่อรูปทรงสินค้า',
    `item_grade_code` String COMMENT 'รหัสเกรดสินค้า',
    `item_grade_name` String COMMENT 'ชื่อเกรดสินค้า',
    `item_model_code` String COMMENT 'รหัสรุ่นสินค้า',
    `item_model_name` String COMMENT 'ชื่อรุ่นสินค้า',
    `item_category_code` String COMMENT 'รหัสหมวดสินค้า',
    `item_category_name` String COMMENT 'ชื่อหมวดสินค้า',
    `item_class_code` String COMMENT 'รหัสระดับสินค้า',
    `item_class_name` String COMMENT 'ชื่อระดับสินค้า',
    `group_main_code` String COMMENT 'รหัสกลุ่มหลัก',
    `group_main_name` String COMMENT 'ชื่อกลุ่มหลัก',
    `group_sub_code` String COMMENT 'รหัสกลุ่มย่อย',
    `group_sub_name` String COMMENT 'ชื่อกลุ่มย่อย',
    `group_sub2_code` String COMMENT 'รหัสกลุ่มย่อย2',
    `group_sub2_name` String COMMENT 'ชื่อกลุ่มย่อย2',
    `description` String COMMENT 'รายละเอียด',
    `status_cancel` String COMMENT 'สถานะยกเลิก Cancel=ยกเลิก',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(doc_datetime)
PRIMARY KEY (doc_datetime, doc_no, branch_code, item_code, branch_sync, branch_sync_name)
ORDER BY (doc_datetime, doc_no, branch_code, item_code, branch_sync, branch_sync_name)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'รายละเอียดเอกสารขาย'

-- Columns for saleinvoice_transaction_detail
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   branch_code: String DEFAULT
--   branch_name: String DEFAULT
--   item_code: String DEFAULT
--   barcode: String DEFAULT
--   item_name: String DEFAULT
--   unit_code: String DEFAULT
--   unit_name: String DEFAULT
--   wh_code: String DEFAULT
--   wh_name: String DEFAULT
--   shelf_code: String DEFAULT
--   shelf_name: String DEFAULT
--   qty: Float64 DEFAULT
--   price: Float64 DEFAULT
--   discount_amount: Float64 DEFAULT
--   sum_amount: Float64 DEFAULT
--   sum_of_cost: Float64 DEFAULT
--   average_cost: Float64 DEFAULT
--   stand_value: Float64 DEFAULT
--   divide_value: Float64 DEFAULT
--   tax_type: String DEFAULT
--   item_brand_code: String DEFAULT
--   item_brand_name: String DEFAULT
--   item_pattern_code: String DEFAULT
--   item_pattern_name: String DEFAULT
--   item_design_code: String DEFAULT
--   item_design_name: String DEFAULT
--   item_grade_code: String DEFAULT
--   item_grade_name: String DEFAULT
--   item_model_code: String DEFAULT
--   item_model_name: String DEFAULT
--   item_category_code: String DEFAULT
--   item_category_name: String DEFAULT
--   item_class_code: String DEFAULT
--   item_class_name: String DEFAULT
--   group_main_code: String DEFAULT
--   group_main_name: String DEFAULT
--   group_sub_code: String DEFAULT
--   group_sub_name: String DEFAULT
--   group_sub2_code: String DEFAULT
--   group_sub2_name: String DEFAULT
--   description: String DEFAULT
--   status_cancel: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

-- stock_transaction (MergeTree)
CREATE TABLE datachangsiam.stock_transaction
(
    `item_code` String COMMENT 'รหัสสินค้า',
    `item_name` String COMMENT 'ชื่อสินค้า',
    `doc_datetime` DateTime COMMENT 'วันที่/เวลา',
    `doc_no` String COMMENT 'เอกสารเลขที่',
    `doc_type` String COMMENT 'ประเภทเอกสาร',
    `ic_unit_code` String COMMENT 'รหัสหน่วยนับ',
    `ic_unit_name` String COMMENT 'ชื่อหน่วยนับ',
    `wh_code` String COMMENT 'รหัสคลัง',
    `wh_name` String COMMENT 'ชื่อคลัง',
    `shelf_code` String COMMENT 'รหัสที่เก็บ',
    `shelf_name` String COMMENT 'ชื่อที่เก็บ',
    `calc_type` String COMMENT 'ประเภทการคำนวณ',
    `qty` Float64 COMMENT 'จำนวน >0=จำนวนเข้า , <0=จำนวนออก',
    `cost` Float64 COMMENT 'ต้นทุนของเอกสาร',
    `amount` Float64 COMMENT 'มูลค่าตามเอกสาร',
    `item_brand_code` String COMMENT 'รหัสยี่ห้อสินค้า',
    `item_brand_name` String COMMENT 'ชื่อยี่ห้อสินค้า',
    `item_pattern_code` String COMMENT 'รหัสรูปแบบสินค้า',
    `item_pattern_name` String COMMENT 'ชื่อรูปแบบสินค้า',
    `item_design_code` String COMMENT 'รหัสรูปทรงสินค้า',
    `item_design_name` String COMMENT 'ชื่อรูปทรงสินค้า',
    `item_grade_code` String COMMENT 'รหัสเกรดสินค้า',
    `item_grade_name` String COMMENT 'ชื่อเกรดสินค้า',
    `item_model_code` String COMMENT 'รหัสรุ่นสินค้า',
    `item_model_name` String COMMENT 'ชื่อรุ่นสินค้า',
    `item_category_code` String COMMENT 'รหัสหมวดสินค้า',
    `item_category_name` String COMMENT 'ชื่อหมวดสินค้า',
    `item_class_code` String COMMENT 'รหัสระดับสินค้า',
    `item_class_name` String COMMENT 'ชื่อระดับสินค้า',
    `group_main_code` String COMMENT 'รหัสกลุ่มหลัก',
    `group_main_name` String COMMENT 'ชื่อกลุ่มหลัก',
    `group_sub_code` String COMMENT 'รหัสกลุ่มย่อย',
    `group_sub_name` String COMMENT 'ชื่อกลุ่มย่อย',
    `group_sub2_code` String COMMENT 'รหัสกลุ่มย่อย2',
    `group_sub2_name` String COMMENT 'ชื่อกลุ่มย่อย2',
    `branch_sync` String COMMENT 'id ของร้าน/บริษัท',
    `branch_sync_name` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(doc_datetime)
PRIMARY KEY item_code
ORDER BY (item_code, wh_code, shelf_code, doc_datetime, doc_no, branch_sync, branch_sync_name)
SETTINGS index_granularity = 8192, min_merge_bytes_to_use_direct_io = 10485760, merge_with_ttl_timeout = 86400, min_bytes_for_wide_part = 0, min_rows_for_wide_part = 0
COMMENT 'เคลื่อนไหวสต็อก'

-- Columns for stock_transaction
--   item_code: String DEFAULT
--   item_name: String DEFAULT
--   doc_datetime: DateTime DEFAULT
--   doc_no: String DEFAULT
--   doc_type: String DEFAULT
--   ic_unit_code: String DEFAULT
--   ic_unit_name: String DEFAULT
--   wh_code: String DEFAULT
--   wh_name: String DEFAULT
--   shelf_code: String DEFAULT
--   shelf_name: String DEFAULT
--   calc_type: String DEFAULT
--   qty: Float64 DEFAULT
--   cost: Float64 DEFAULT
--   amount: Float64 DEFAULT
--   item_brand_code: String DEFAULT
--   item_brand_name: String DEFAULT
--   item_pattern_code: String DEFAULT
--   item_pattern_name: String DEFAULT
--   item_design_code: String DEFAULT
--   item_design_name: String DEFAULT
--   item_grade_code: String DEFAULT
--   item_grade_name: String DEFAULT
--   item_model_code: String DEFAULT
--   item_model_name: String DEFAULT
--   item_category_code: String DEFAULT
--   item_category_name: String DEFAULT
--   item_class_code: String DEFAULT
--   item_class_name: String DEFAULT
--   group_main_code: String DEFAULT
--   group_main_name: String DEFAULT
--   group_sub_code: String DEFAULT
--   group_sub_name: String DEFAULT
--   group_sub2_code: String DEFAULT
--   group_sub2_name: String DEFAULT
--   branch_sync: String DEFAULT
--   branch_sync_name: String DEFAULT

